### ISSUE TITLE
Requesting permissions to Camera on launch

### ISSUE THREAD

**Issue by gtfargo** [react-native-ar/react-native-arkit#132]
react-native-arkit unfavorably requests access to the camera on app launch.  How might I delay this until the ARKit view is actually mounted in my application?  

I already have permission handling for the camera built into the onboarding flow of my app (before ARKit is used).  I would like to keep the UX as is, instead of hitting users with an alert at launch.

**Comment by gtfargo** [comment]
In `initWithARView`, after initializing, `[self resume];`  is called.  Is there a reason for this?   Removing this line has done the trick for me.

**Comment by gtfargo** [comment]
https://github.com/HippoAR/react-native-arkit/pull/138

**Comment by macrozone** [comment]
@gtfargo can you chekc if https://github.com/HippoAR/react-native-arkit/pull/152 solves your issue as well?
