### ISSUE TITLE
Running animation on a .scn Model

### ISSUE THREAD

**Issue by cineconcerts** [react-native-ar/react-native-arkit#190]
I'm loading an animated .scn as a model but the animation doesn't run when loaded. How do I trigger an .scn to run its animation?

**Comment by jwanga** [comment]
Any Ideas?

**Comment by harishsn** [comment]
need help

**Comment by macrozone** [comment]
this repo is no longer maintained. I recommend to give https://github.com/ViroCommunity/viro a try which has a similar api and supports android as well.
