### ISSUE TITLE
This package not working on XCode 10

### ISSUE THREAD

**Issue by WestFR** [react-native-ar/react-native-arkit#203]
Hello,

Because I have some issues on this package, i have explore some tests today for find the origin problem.

I have tested all testing app provided in your readme and in apps used.

All apps used XCode 9 to compile and build app on real device.

However, now, we need to compile and build this package on XCode 10 to publish on AppStore such as mentionned by Apple.

So, this package need an upgrade for works on lastest version of react-native and XCode 10.

Multiple users may be able to use this package within a production application. 

And actually, with this problem, it's simply impossible. 

Thanks all.

**Comment by code-matt** [comment]
Don't think anyone can help without seeing the errors.

I was building on 10.1 for a long while now, never tried on 9. XCode 11.0 beta 3 with ios13 works as well. As long as you go to RN 59.9 to avoid this error https://github.com/facebook/react-native/issues/25138

Now going to 60.0 😓 that is another issue but it's not just this module

**Comment by WestFR** [comment]
Some issues provided by react-native and somes modules make this package unstable.

React-native is not for production application at all. Hybrid app are crapped.
Native development is the best. And react-native is a big big shit !
