### ISSUE TITLE
does this support body detection ?

### ISSUE THREAD

**Issue by ortegatron** [react-native-ar/react-native-arkit#207]
Hi all, as the title says, I'm wondering whether this component provides access to the body detection utilities of the ARKit3 
I've been reading the docs but can't find any mention, should I assume it doesn't?   
thanks

**Comment by macrozone** [comment]
Hi @ortegatron! unfortunatly not as I could not maintain this library anymore for some time. Even Arkit2 is not supported yet, altough it would not be too hard to add these features.

You might also look at https://viromedia.com/, they have a react-native library which works both in ios and android has a very similar api to react-native-arkit

**Comment by ortegatron** [comment]
Oh I see. Thanks for the answer, closing the issue.

**Comment by prashant-wxit** [comment]
> Hi @ortegatron! unfortunatly not as I could not maintain this library anymore for some time. Even Arkit2 is not supported yet, altough it would not be too hard to add these features.
> 
> You might also look at https://viromedia.com/, they have a react-native library which works both in ios and android has a very similar api to react-native-arkit

I think WebSite Expired 
![image](https://user-images.githubusercontent.com/61351038/159414174-409fb29d-2a40-4ad2-aee3-d093edcb8f85.png)
